FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /build
COPY . .

RUN mvn -f pom.xml clean package -pl Services/fx-service -am -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /build/Services/fx-service/target/*.jar app.jar

EXPOSE 8080

CMD ["sh", "-c", "java -Dserver.port=${PORT:-8080} -jar /app/app.jar"]
