-- CORRECCIÓN — la sintaxis anterior era de H2/Postgres, SQLite no la soporta
-- BIGINT GENERATED BY DEFAULT AS IDENTITY no existe en SQLite
CREATE TABLE IF NOT EXISTS debtors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    document TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    phone TEXT
);